
spring:
  # DataBase 접속정보 설정
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3307/test
    driver-class-name: org.mariadb.jdbc.Driver
  # ViewTemplate thymeleaf ?? set
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      location: /fileupload
      max-request-size: 50MB

# mybatis 설정
mybatis:
  mapper-locations:
    - classpath:config/mapper/NoticeBoard.xml
  configuration:
    # snake_case -> camelCase ??
    map-underscore-to-camel-case: true

# ?? ???? ??
file:
  root-path: /fileupload

logging:
  config: classpath:config/logback.xml

