spring:
  # DataBase 접속정보 설정
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3307/ToyProject
    driver-class-name: org.mariadb.jdbc.Driver

  # ViewTemplate thymeleaf ?? set
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      location: /fileupload
      max-request-size: 50MB

  web:
    resources:
      static-locations: classpath:/static/

# mybatis 설정
mybatis:
  mapper-locations:
    - classpath:config/mapper/**.xml
  configuration:
    # snake_case -> camelCase ??
    map-underscore-to-camel-case: true

# ?? ???? ??
file:
  root-path: /fileupload

logging:
  config: classpath:config/logback.xml

security:
  form-login:
  username-parameter: "loginId"
  password-parameter: "loginPwd"
  login-processing-url: "/login"
  login-page: "/login"
  authentication-success-handler-ref: "loginSuccessHandler"
